### ISSUE TITLE
Does this package only contain 13 extensions?

### ISSUE THREAD

**Issue by DanielSWolf** [bevry/binaryextensions#107]
According to the README, this package contains "every single file extension there is for binary files". While this is a somewhat bold claim, I'd have expected to see at least a few hundred file extensions. But [looking at _index.ts_](https://github.com/bevry/binaryextensions/blob/master/source/index.ts), it seems to me that this package contains only 13 file extensions, thus missing even common ones like .ogg, .mp3, or .docx.

Am I missing something?

**Comment by balupton** [comment]
Send a PR for the missing ones, that is the only way your divergent knowledge will be consolidated into this definitive listing. In the same way Wikipedia is the encyclopaedia for the world's knowledge.

Here's the edit link:

https://github.com/bevry/binaryextensions/edit/master/source/index.ts

Your contribution will go to improve binary/text identification performance in millions of installs a month.
