### ISSUE TITLE
npm install binaryextensions@2.3.0 not working in node v6.3.0 and npm v3.10.3

### ISSUE THREAD

**Issue by abhinavbansal19961996** [bevry/binaryextensions#40]
For node v6.3.0, npm v3.10.3
npm i binaryextensions@2.3.0 is not working and throwing error whereas
npm I binaryextensions@2.2.0 is working correctly.
There seem to be some problem with 2.3.0 version and its compatibility with node and npm version. Can you please confirm whether it is an issue and fix it.

.13:26:36 npm ERR! node v6.3.0
13:26:36 npm ERR! npm  v3.10.3
13:26:36 npm ERR! code EMISSINGARG
13:26:36 
13:26:36 npm ERR! typeerror Error: Missing required argument #1
13:26:36 npm ERR! typeerror     at andLogAndFinish 
(/apps/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs6.3.0/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)

**Comment by ahujaisonline** [comment]
same. ^^ it's weird, stopped working all of sudden. 

Few changes were pushed 5 days ago.
https://github.com/bevry/binaryextensions/commit/ef9b2c72390c77a8cf4de2b74be7ab82b4af2d59
https://github.com/bevry/binaryextensions/commit/80a0f07d26e5d39a97d5e1df93b724a226fb0e79

**Comment by balupton** [comment]
The only thing I can think it would be would be the introduction of "type": "commonjs" to the package.json file, which may not support json files in older npm/node versions.
https://github.com/bevry/binaryextensions/commit/ef9b2c72390c77a8cf4de2b74be7ab82b4af2d59#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R84

I'll rewrite it as a ts file that generates a json file, when I start work

**Comment by balupton** [comment]
However, why are you using node v6, that was discontinued (with no security patches anymore) years ago

**Comment by abhinavbansal19961996** [comment]
Ya. We will be upgrading it to latest versions soon.

**Comment by balupton** [comment]
fixed in latest release, applying changes to textextensions and istextorbinary now

**Comment by balupton** [comment]
changes applied everywhere
